#!/usr/bin/env python3
"""
WAV to MMP Converter
Converts mono 16-bit WAV files to ZeroPoint APU MMP format

Usage: python3 wav2mmp.py input.wav output.inc [options]

Output format:
  - SST blocks (16 bytes each: 4-byte header + 12 PCM samples)
  - STL entry (4 bytes: sample address + loop address)
  - Assembly .inc file ready to include in APU programs
"""

import struct
import sys
import wave
import argparse
from pathlib import Path


def read_wav(filename):
    """Read WAV file and return sample data"""
    with wave.open(filename, 'rb') as wav:
        # Verify format
        channels = wav.getnchannels()
        sample_width = wav.getsampwidth()
        framerate = wav.getframerate()
        n_frames = wav.getnframes()

        print(f"Input WAV: {channels}ch, {sample_width*8}-bit, {framerate} Hz, {n_frames} samples")

        if channels != 1:
            print(f"Warning: Input is {channels} channels, will mix to mono")

        if sample_width != 2:
            print(f"Warning: Input is {sample_width*8}-bit, expected 16-bit")

        # Read all frames
        raw_data = wav.readframes(n_frames)

        # Parse based on format
        if sample_width == 2:  # 16-bit
            samples = []
            for i in range(0, len(raw_data), 2 * channels):
                # Read first channel (or mix if stereo)
                if channels == 1:
                    sample = struct.unpack('<h', raw_data[i:i+2])[0]
                else:  # Mix stereo to mono
                    left = struct.unpack('<h', raw_data[i:i+2])[0]
                    right = struct.unpack('<h', raw_data[i+2:i+4])[0]
                    sample = (left + right) // 2
                samples.append(sample)
        elif sample_width == 1:  # 8-bit
            samples = []
            for i in range(0, len(raw_data), channels):
                sample = raw_data[i] - 128  # Convert unsigned to signed
                sample = sample * 256  # Scale to 16-bit range
                samples.append(sample)
        else:
            raise ValueError(f"Unsupported sample width: {sample_width}")

        return samples, framerate


def downsample_to_8bit(samples_16bit):
    """Convert 16-bit signed samples to 8-bit signed"""
    samples_8bit = []
    for sample in samples_16bit:
        # Scale from 16-bit (-32768 to 32767) to 8-bit (-128 to 127)
        sample_8 = sample // 256
        # Clamp to 8-bit range
        sample_8 = max(-128, min(127, sample_8))
        samples_8bit.append(sample_8)
    return samples_8bit


def create_sst_blocks(samples_8bit, loop=True):
    """
    Create SST blocks from 8-bit samples

    SST block format (16 bytes):
      Byte 0:   Loop count (XX) - 0xFF for continuous loop
      Byte 1:   Y (loop start) in upper nybble, L (config) in lower nybble
                L bits: ZW00 where W=1 for final block
      Byte 2:   V (upper nybble), U (lower nybble) - clamping samples
      Byte 3:   T (upper nybble), S (lower nybble) - clamping amounts
      Bytes 4-15: 12 PCM samples (8-bit signed)
    """
    blocks = []

    # Pad to multiple of 12 samples
    while len(samples_8bit) % 12 != 0:
        samples_8bit.append(0)

    num_blocks = len(samples_8bit) // 12

    for block_idx in range(num_blocks):
        block = bytearray(16)

        # Header byte 0: Loop count
        if loop:
            block[0] = 0xFF  # Loop 255 times
        else:
            block[0] = 0x00  # Play once

        # Header byte 1: Y (loop from sample 0) and L (config)
        # Y = 0 (loop from first sample)
        # L = 0x4 if final block (W bit set), else 0x0
        is_final = (block_idx == num_blocks - 1)
        Y = 0  # Loop from sample 0
        L = 0x4 if is_final else 0x0  # W bit (bit 2)
        block[1] = (Y << 4) | L

        # Header bytes 2-3: Clamping (disabled for now)
        block[2] = 0x00  # V=0, U=0
        block[3] = 0x00  # T=0, S=0

        # Sample data (bytes 4-15)
        for i in range(12):
            sample_idx = block_idx * 12 + i
            # Convert signed to unsigned byte for storage
            sample_signed = samples_8bit[sample_idx]
            sample_unsigned = sample_signed & 0xFF
            block[4 + i] = sample_unsigned

        blocks.append(bytes(block))

    return blocks


def generate_inc_file(blocks, output_path, sst_address=0x9000, stl_address=0x7000, label_prefix="sfx"):
    """Generate .inc assembly file"""
    lines = []

    lines.append(f"; Generated by wav2mmp.py")
    lines.append(f"; SST blocks: {len(blocks)} ({len(blocks) * 16} bytes)")
    lines.append(f"; SST address: ${sst_address:04X}")
    lines.append(f"; STL address: ${stl_address:04X}")
    lines.append("")

    # SST data label
    lines.append(f"{label_prefix}_sst_data:")

    # Generate SST blocks
    for block_idx, block in enumerate(blocks):
        lines.append(f"    ; Block {block_idx}")

        # Header (4 bytes)
        lines.append(f"    ; Header: loops=${block[0]:02X}, Y/L=${block[1]:02X}, V/U=${block[2]:02X}, T/S=${block[3]:02X}")
        for i in range(0, 4, 2):
            lines.append(f"    WRH ${block[i]:02X}")
            lines.append(f"    WRL ${block[i+1]:02X}")

        # Samples (12 bytes)
        lines.append(f"    ; Samples (12 bytes)")
        for i in range(4, 16, 2):
            lines.append(f"    WRH ${block[i]:02X}")
            lines.append(f"    WRL ${block[i+1]:02X}")

        lines.append("")

    # STL entry
    lines.append(f"{label_prefix}_stl_entry:")
    lines.append(f"    ; Sample data address = ${sst_address:04X}")
    lines.append(f"    WRH ${(sst_address >> 8):02X}")
    lines.append(f"    WRL ${(sst_address & 0xFF):02X}")
    lines.append(f"    ; Loop address = 0 (loop entire sample)")
    lines.append(f"    WRH $00")
    lines.append(f"    WRL $00")
    lines.append("")

    # Usage example
    lines.append(f"; Usage example:")
    lines.append(f";   SDP ${(sst_address >> 8):02X}      ; Set DP to SST page")
    lines.append(f";   SDB $00")
    lines.append(f";   {label_prefix}_sst_data        ; Write SST blocks")
    lines.append(f";")
    lines.append(f";   SDP ${(stl_address >> 8):02X}      ; Set DP to STL page")
    lines.append(f";   SDB $00")
    lines.append(f";   {label_prefix}_stl_entry       ; Write STL entry")
    lines.append(f";")
    lines.append(f";   ; Configure channel 0 to play")
    lines.append(f";   SDP $00              ; MMP registers")
    lines.append(f";   SDB $00")
    lines.append(f";   WRH $10              ; Pitch = 0x1000 (1.0x)")
    lines.append(f";   WRL $00")
    lines.append(f";   SDB $20")
    lines.append(f";   SBF 0")
    lines.append(f";   SCR X, 128           ; Volume = 128")
    lines.append(f";   STA X, $20")
    lines.append(f";   SDB $54")
    lines.append(f";   WRH ${(stl_address >> 8):02X}      ; STL address -> starts playback")
    lines.append(f";   WRL ${(stl_address & 0xFF):02X}")

    # Write to file
    with open(output_path, 'w') as f:
        f.write('\n'.join(lines))

    print(f"Generated {output_path}")
    print(f"  Blocks: {len(blocks)}")
    print(f"  Total size: {len(blocks) * 16} bytes")


def main():
    parser = argparse.ArgumentParser(description='Convert WAV to ZeroPoint APU MMP format')
    parser.add_argument('input', help='Input WAV file (mono 16-bit recommended)')
    parser.add_argument('output', help='Output .inc file')
    parser.add_argument('--sst-addr', default='0x9000', help='SST base address (default: 0x9000)')
    parser.add_argument('--stl-addr', default='0x7000', help='STL base address (default: 0x7000)')
    parser.add_argument('--label', default='sfx', help='Label prefix (default: sfx)')
    parser.add_argument('--no-loop', action='store_true', help='Don\'t loop sample (play once)')

    args = parser.parse_args()

    # Parse addresses
    sst_addr = int(args.sst_addr, 16) if args.sst_addr.startswith('0x') else int(args.sst_addr)
    stl_addr = int(args.stl_addr, 16) if args.stl_addr.startswith('0x') else int(args.stl_addr)

    print(f"Converting {args.input} -> {args.output}")

    # Read WAV
    samples_16bit, sample_rate = read_wav(args.input)
    print(f"Read {len(samples_16bit)} samples")

    # Convert to 8-bit
    samples_8bit = downsample_to_8bit(samples_16bit)
    print(f"Converted to 8-bit: {len(samples_8bit)} samples")

    # Create SST blocks
    blocks = create_sst_blocks(samples_8bit, loop=not args.no_loop)
    print(f"Created {len(blocks)} SST blocks")

    # Generate .inc file
    generate_inc_file(blocks, args.output, sst_addr, stl_addr, args.label)

    print("\nConversion complete!")


if __name__ == '__main__':
    main()
